package org.exeval.utilities

import org.exeval.utilities.interfaces.TokenCategory

enum class TokenCategories(val regex: String) : TokenCategory {
	PunctuationSemicolon(";"),
	PunctuationColon(":"),
	PunctuationComma(","),
	PunctuationArrow("->"),
	PunctuationMonkey("@"),
	PunctuationLeftCurlyBracket("{"),
	PunctuationRightCurlyBracket("}"),
	PunctuationLeftRoundBracket("\\("),
	PunctuationRightRoundBracket("\\)"),
	LiteralInteger("(\\d)(\\d)*"),
	LiteralBoolean("(true|false)"),
	LiteralNope("\\(\\)"),
	OperatorPlus("+"),
	OperatorMinus("-"),
	OperatorStar("\\*"),
	OperatorDivision("/"),
	OperatorOr("or"),
	OperatorAnd("and"),
	OperatorNot("not"),
	OperatorGreater(">"),
	OperatorLesser("<"),
	OperatorGreaterEqual(">="),
	OperatorLesserEqual("<="),
	OperatorEqual("=="),
	OperatorNotEqual("!="),
	OperatorAssign("="),
	KeywordIf("if"),
	KeywordThen("then"),
	KeywordElse("else"),
	KeywordLoop("loop"),
	KeywordFoo("foo"),
	KeywordBreak("break"),
	KeywordReturn("return"),
	KeywordLet("let"),
	KeywordMut("mut"),
	IdentifierType("\\u(\\l|\\u)*"),
	IdentifierNontype("(\\l|_)(\\i)*"),
	IdentifierEntrypoint("main"),
	Whitespace("\\s");
}
