package org.exeval.cfg

enum class TreeKind {
    CONSTANT,
    MEMORY,
    REGISTER,
    ASSIGNMENT,
    BINARY_ADD, BINARY_SUBTRACT, BINARY_MULTIPLY, BINARY_DIVIDE, BINARY_AND, BINARY_OR, BINARY_GREATER, BINARY_GREATER_EQUAL, BINARY_EQUAL, BINARY_LESS, LESS_EQUAL,
    UNARY_NOT, UNARY_MINUS,
    CALL,
    RETURN
}